(function (root) {
  const translations = {
    adequate: "重要考试前，充足的睡眠是必要的。",
    ensure: "父母应确保孩子获得足够的睡眠。",
    immunity: "经常锻炼可以增强我们的免疫力。",
    nutrition: "均衡饮食能提供充足的营养。",
    optimistic: "Nelson 对自己的进步持乐观态度。",
    attention: "我们应该更加关注日常健康。",
    convenient: "科技让我们的生活变得更加方便。",
    pollution: "更多汽车可能导致严重的空气污染。",
    burden: "垃圾给环境造成了沉重负担。",
    vital: "清洁的水在日常生活中起着至关重要的作用。",
    recyclable: "纸张和瓶子通常属于可回收垃圾。",
    significant: "微小的行动也能产生显著影响。",
    efficient: "清晰的计划能让晨读更加高效。",
    benefit: "每天朗读会让 Nelson 受益。",
    available: "网上可以获得更多听力材料。",
    access: "学生可以更方便地接触真实材料。",
    rely: "我们不应该完全依赖翻译软件。",
    impact: "练习能对写作产生持久影响。",
    consistent: "持续练习是词汇增长的关键。",
    achieve: "他希望一步一步实现自己的目标。",
    concentrate: "房间嘈杂时很难集中注意力。",
    progress: "Nelson 在朗读方面取得了很大进步。",
    evidence: "几乎没有证据支持这一说法。",
    persuade: "演讲者未能说服听众。",
    accurate: "准确的翻译并不总是优美的翻译。",
    knowledge: "阅读帮助学生获得有用的知识。",
    analyze: "学生应该分析作者的写作目的。",
    logical: "一篇好文章需要合乎逻辑的结构。",
    summarize: "你能用一句话总结这篇文章吗？",
    broaden: "广泛阅读可以拓宽我们的视野。",
    transfer: "目标是把新词迁移到写作中。",
    apply: "学生应该把有用的表达运用到作文中。",
    replace: "我们可以用更准确的词替换简单词。",
    specific: "有力的段落需要具体例子。",
    complex: "Nelson 正在学习写更复杂的句子。",
    coherent: "一篇好文章应该清晰且连贯。",
    strength: "每个人在语言学习中都有自己的优势。",
    weakness: "了解自己的弱点是进步的第一步。",
    improve: "每日练习会提高 Nelson 的写作能力。",
    clarify: "你能阐明这句话的意思吗？",
  };
  const words = [
    ["adequate", "足够的", "A_______ sleep is necessary before an important exam.", "spelling", "recent", 5],
    ["ensure", "确保", "Parents should e_______ that children get enough sleep.", "grammar", "recent", 5],
    ["immunity", "免疫力", "Regular exercise can improve our i_______.", "spelling", "recent", 4],
    ["nutrition", "营养", "A balanced diet provides enough n_______.", "word-form", "recent", 4],
    ["optimistic", "乐观的", "Nelson is o_______ about his progress.", "spelling", "recent", 4],
    ["attention", "关注", "We should pay more a_______ to daily health.", "collocation", "recent", 5],
    ["convenient", "方便的", "Technology has made our life more c_______.", "word-form", "recent", 3],
    ["pollution", "污染", "More cars may lead to serious air p_______.", "word-form", "recent", 4],
    ["burden", "负担", "Waste places a heavy b_______ on the environment.", "collocation", "recent", 4],
    ["vital", "至关重要的", "Clean water plays a v_______ role in daily life.", "collocation", "recent", 5],
    ["recyclable", "可回收的", "Paper and bottles are usually r_______ waste.", "spelling", "recent", 4],
    ["significant", "显著的", "Small actions can have a s_______ influence.", "spelling", "recent", 5],
    ["efficient", "高效的", "A clear plan makes morning reading more e_______.", "word-form", "previous", 4],
    ["benefit", "使受益", "Reading aloud every day will b_______ Nelson.", "grammar", "previous", 4],
    ["available", "可获得的", "More listening materials are a_______ online.", "spelling", "previous", 3],
    ["access", "使用权", "Students have easier a_______ to authentic materials.", "collocation", "previous", 5],
    ["rely", "依赖", "We should not r_______ completely on translation software.", "collocation", "previous", 5],
    ["impact", "影响", "Practice can have a lasting i_______ on writing.", "collocation", "previous", 4],
    ["consistent", "持续的", "C_______ practice is the key to vocabulary growth.", "spelling", "previous", 5],
    ["achieve", "实现", "He hopes to a_______ his goal step by step.", "collocation", "previous", 4],
    ["concentrate", "集中注意力", "It is hard to c_______ when the room is noisy.", "collocation", "previous", 4],
    ["progress", "进步", "Nelson has made great p_______ in reading aloud.", "grammar", "previous", 5],
    ["evidence", "证据", "There is little e_______ to support the claim.", "grammar", "mistake", 5],
    ["persuade", "说服", "The speaker failed to p_______ the audience.", "collocation", "mistake", 4],
    ["accurate", "准确的", "An a_______ translation is not always beautiful.", "spelling", "mistake", 4],
    ["knowledge", "知识", "Reading helps students gain useful k_______.", "grammar", "mistake", 5],
    ["analyze", "分析", "Students should a_______ the writer's purpose.", "spelling", "mistake", 4],
    ["logical", "合乎逻辑的", "A good essay needs a l_______ structure.", "word-form", "monthly-vocabulary", 5],
    ["summarize", "总结", "Can you s_______ the passage in one sentence?", "spelling", "monthly-vocabulary", 4],
    ["broaden", "拓宽", "Reading widely can b_______ our horizons.", "collocation", "monthly-vocabulary", 5],
    ["transfer", "迁移", "The goal is to t_______ new words into writing.", "collocation", "monthly-vocabulary", 4],
    ["apply", "应用", "Students should a_______ useful expressions to essays.", "collocation", "monthly-vocabulary", 5],
    ["replace", "替换", "We can r_______ simple words with accurate ones.", "collocation", "monthly-vocabulary", 5],
    ["specific", "具体的", "A strong paragraph needs s_______ examples.", "spelling", "monthly-vocabulary", 4],
    ["complex", "复杂的", "Nelson is learning to write c_______ sentences.", "spelling", "monthly-vocabulary", 4],
    ["coherent", "连贯的", "A good essay should be clear and c_______.", "spelling", "monthly-vocabulary", 5],
    ["strength", "优势", "Everyone has a s_______ in language learning.", "spelling", "monthly-vocabulary", 4],
    ["weakness", "弱点", "Knowing your w_______ is the first step to improvement.", "spelling", "monthly-vocabulary", 4],
    ["improve", "提高", "Daily practice will i_______ Nelson's writing.", "collocation", "monthly-vocabulary", 4],
    ["clarify", "阐明", "Could you c_______ what you mean?", "spelling", "monthly-vocabulary", 3],
  ];

  const spellingQuestions = words.map((word, index) => ({
    id: `word-${index + 1}`,
    knowledgeId: `word:${word[0]}`,
    knowledge: word[0],
    prompt: word[2],
    instruction: `根据中文提示「${word[1]}」补全单词。`,
    type: "input",
    kind: "句中拼写",
    category: word[3] === "grammar" ? "grammar" : word[3] === "collocation" ? "collocation" : "spelling",
    scope: word[4],
    answer: word[0],
    accepted: [word[0]],
    errorType: word[3],
    importance: word[5],
    explanation: `正确答案是 ${word[0]}。注意它在句中的拼写和用法。`,
    translation: translations[word[0]],
    variantPrompt: word[2].replace(/^[A-Z]_______|[a-zA-Z]_______/, "_____"),
  }));

  const grammarQuestions = [
    ["grammar:evidence-uncountable", "evidence 不可数", "There _____ enough evidence to support the conclusion.", ["is", "are", "were", "have"], "is", "evidence 通常是不可数名词，谓语使用单数。", "有足够的证据支持这个结论。"],
    ["grammar:only-if-inversion", "Only if 倒装", "Only if we review regularly _____ vocabulary knowledge be transformed into writing competence.", ["can", "it can", "vocabulary can", "can it"], "can", "Only if 位于句首时，主句使用部分倒装：can vocabulary knowledge be transformed...", "只有定期复习，词汇知识才能转化为写作能力。"],
    ["grammar:ensure-that", "ensure that 从句", "We must ensure that Nelson _____ adequate sleep.", ["get", "gets", "getting", "to get"], "gets", "that 从句主语 Nelson 是第三人称单数。", "我们必须确保 Nelson 获得充足的睡眠。"],
    ["grammar:pay-attention-to", "pay attention to", "Please pay attention _____ the verb form.", ["at", "for", "to", "with"], "to", "pay attention to 是固定搭配，to 是介词。", "请注意动词的形式。"],
    ["grammar:rely-on", "rely on", "We should not rely _____ translation software completely.", ["in", "at", "on", "for"], "on", "rely on/upon 表示“依赖”。", "我们不应该完全依赖翻译软件。"],
    ["grammar:access-to", "have access to", "Students now have easier access _____ authentic materials.", ["for", "to", "with", "of"], "to", "have access to 中的 to 是介词。", "学生现在可以更方便地接触真实材料。"],
    ["grammar:because-of", "because of", "_____ consistent practice, Nelson is making progress.", ["Because", "Because of", "Although", "Unless"], "Because of", "because of 后接名词短语；because 后接完整句子。", "由于持续练习，Nelson 正在取得进步。"],
    ["grammar:present-perfect", "现在完成时", "Modern technology _____ English learning more efficient.", ["made", "has made", "makes yesterday", "is making last week"], "has made", "强调过去发生并影响现在，使用现在完成时。", "现代科技已经让英语学习变得更加高效。"],
    ["grammar:passive-voice", "被动语态", "Recyclable waste can _____ to save resources.", ["utilize", "be utilized", "be utilizing", "utilized"], "be utilized", "情态动词后被动结构为 can be + 过去分词。", "可回收垃圾可以被利用来节约资源。"],
    ["grammar:not-only", "not only...but also", "Reading widely can not only expand our vocabulary _____ enrich our knowledge.", ["and", "but also", "or", "so"], "but also", "not only...but also... 是固定并列结构。", "广泛阅读不仅能扩大词汇量，还能丰富知识。"],
  ].map((item, index) => ({
    id: `grammar-${index + 1}`,
    knowledgeId: item[0],
    knowledge: item[1],
    prompt: item[2],
    instruction: "选择最准确的答案。",
    type: "choice",
    kind: "语法选择",
    category: "grammar",
    scope: index < 5 ? "mistake" : "monthly-grammar",
    options: item[3],
    answer: item[4],
    accepted: [item[4]],
    errorType: "grammar",
    importance: index < 5 ? 5 : 4,
    explanation: item[5],
    translation: item[6],
    variantPrompt: `换一个语境继续考查「${item[1]}」。`,
  }));

  root.NELSON_WEEK_DATA = {
    weekId: "2026-W24",
    label: "WEEK 04",
    dateRange: "2026-06-13 至 2026-06-19",
    questions: [...spellingQuestions, ...grammarQuestions],
  };
})(typeof window !== "undefined" ? window : globalThis);
